<?php
/**
 * @file
 * Code for the Catalyst Page feature.
 */

include_once 'catalyst_page.features.inc';

/**
 * Implements hook_ctools_plugin_directory().
 */
function catalyst_page_ctools_plugin_directory($owner, $plugin_type) {
  if ($owner == 'catalyst_core') return 'plugins/' . $plugin_type;
}

/**
 * Implements hook_entity_view().
 */
function catalyst_page_entity_view($entity, $entity_type, $view_mode, $page = FALSE) {
  if ($entity_type == 'catalyst' && $entity->type == 'page') {
    $entity->setVariable('title', drupal_get_title());
  }
}

function catalyst_page_preprocess_page_content(&$variables) {
  $template = $variables['template'];

  $pathvars = array();
  if ($path = $template->getMenuPath()) {
    if ($pathvars = catalyst_menu_parse_path($path)) {
      $variables = array_merge($variables, $pathvars);
    }
  }

  // Custom processing defined by the page
  if ($preprocess_php = $template->getPreprocessPHP()) {
    catalyst_eval($preprocess_php, $variables, $pathvars);
  }

  // Custom HTML head defined by the page
  if ($custom_html_head = $template->getHTMLHead()) {
    drupal_add_html_head(
      array(
        '#type' => 'markup',
        '#markup' => $custom_html_head . "\n",
      ),
      'catalyst_page_html_head'
    );
  }
}

function theme_page_content($variables) {
  return $variables['template']->renderTemplate($variables);
}
