<?php
/**
 * @file
 * Code for the Catalyst Core feature.
 */

include_once 'catalyst_core.features.inc';
include_once 'common/registry.inc';

define('CATALYST_CSS_SYSTEM', -101);
define('CATALYST_CSS_LAYOUT', 101);
define('CATALYST_CSS_PAGE', 201);
define('CATALYST_CSS_OTHER', 301);

define('CATALYST_JS_SYSTEM', -201);
define('CATALYST_JS_LIBRARY', -101);
define('CATALYST_JS_LAYOUT', 101);
define('CATALYST_JS_PAGE', 201);
define('CATALYST_JS_OTHER', 301);

/**
 * Implements hook_ctools_plugin_type().
 */
function catalyst_core_ctools_plugin_type() {
  return array(
    'plugin' => array(
      'child plugins' => TRUE,
    ),
    'bundle' => array(
      'child plugins' => TRUE,
      'process' => array(
        'function' => 'catalyst_process_bundle_plugin',
        'file' => 'plugins.inc',
        'path' => catalyst_get_path('includes'),
      ),
    )
  );
}

/**
 * Implements hook_ctools_plugin_directory().
 */
function catalyst_core_ctools_plugin_directory($owner, $plugin_type) {
  if ($owner == 'catalyst_core') {
    if ($plugin_type == 'plugin') return 'plugins/catalyst';
    return 'plugins/'. $plugin_type;
  }
}

/**
 * Implements hook_theme().
 */
function catalyst_core_theme() {
  catalyst_include('plugins');
  $return = catalyst_invoke_all('theme');
  return $return;
}

/**
 * Implements hook_action_info().
 */
function catalyst_core_action_info() {
  // Action callbacks have to be inside the module AFAIK
  return array(
    'catalyst_update_package_action' => array(
      'type' => 'catalyst',
      'label' => t('Set or change package'),
      'configurable' => TRUE,
      'triggers' => array('any'),
    ),
    'catalyst_set_realm_system_action' => array(
      'type' => 'catalyst',
      'label' => t('Send to system realm'),
      'configurable' => FALSE,
      'triggers' => array('any'),
    ),
    'catalyst_set_realm_site_action' => array(
      'type' => 'catalyst',
      'label' => t('Send to site realm'),
      'configurable' => FALSE,
      'triggers' => array('any'),
    ),
  );
}

/**
 * Implements hook_entity_info_alter().
 */
function catalyst_core_entity_info_alter(&$entity_info) {
  $entity_info['catalyst']['controller class'] = 'CatalystEntityAPIController';
  $entity_info['catalyst']['access callback'] = 'catalyst_entity_access_strict';
  $entity_info['catalyst']['entity class'] = 'CatalystEntity';
  $entity_info['catalyst']['view modes'] = array();
  unset($entity_info['catalyst']['translation']);

  if (!isset($entity_info['catalyst']['bundles']['package'])) return;
  catalyst_include('plugins');
  $bundles = catalyst_get_plugins('bundle');
  foreach ($bundles AS $bundle => $bundle_plugin) {
    if (strpos($bundle, ':')) list($parent, $bundle) = explode(':', $bundle);
    if (empty($entity_info['catalyst']['bundles'][$bundle])) continue;
    $entity_info['catalyst']['bundles'][$bundle] = array_merge(
      $entity_info['catalyst']['bundles'][$bundle],
      $bundle_plugin
    );
  }
  catalyst_invoke_alter_all('catalyst entity info alter', $entity_info['catalyst']);
  catalyst_invoke_alter_all('hook entity info alter', $entity_info);
}

/**
 * Get info about catalyst types.
 */
function catalyst_get_plugin_info($plugin = NULL, $reset = NULL) {
  $stored_info = &drupal_static(__FUNCTION__);
  if ($reset || !isset($stored_info)) {
    foreach (module_implements('catalyst_plugin_info') AS $module) {
      foreach (module_invoke($module, 'catalyst_plugin_info') as $type => $info) {
        $stored_info[$type] = $info + array(
          'module' => $module,
          'exportables' => FALSE,
        );
      }
    }
    drupal_alter('catalyst_plugin_info', $stored_info);
  }
  if ($plugin) {
    return isset($stored_info[$plugin]) ? $stored_info[$plugin] : FALSE;
  }
  return $stored_info;
}

/**
 * Implements hook_hook_info().
 */
function catalyst_core_hook_info() {
  $group = array('group' => 'catalyst');
  // Plugin hooks
  $hooks['catalyst_plugin_info'] = $group;
  $hooks['catalyst_plugin_info_alter'] = $group;
  // Export hooks
  $hooks['catalyst_export_dependencies'] = $group;
  $hooks['catalyst_export_candidates'] = $group;
  $hooks['catalyst_prepare_export'] = $group;
  $hooks['catalyst_export_alter'] = $group;
  // Menu hooks
  $hooks['catalyst_ignore_menus'] = $group;
  $hooks['catalyst_ignore_menus_alter'] = $group;
  // Twig
  $hooks['catalyst_twig_alter'] = $group;
  // Fields, entities, and node related hooks
  $hooks['catalyst_safe_fields'] = $group;
  $hooks['catalyst_import_alter'] = $group;
  $hooks['catalyst_export_metadata'] = $group;
  $hooks['catalyst_export_component'] = $group;
  $hooks['catalyst_registry_alter'] = $group;
  return $hooks;
}

/**
 * Implements hook_menu_alter().
 */
function catalyst_core_menu_alter(&$menu_items) {
  $path = 'admin/reports/fields';
  if (isset($menu_items[$path])) {
    $menu_items[$path] = array_merge($menu_items[$path], array(
      'page callback' => 'catalyst_field_ui_clean_field_list',
      'file path' => catalyst_get_path('includes'),
      'module' => 'catalyst_core',
      'file' => 'fields.inc',
    ));
  }
  $entity_info = entity_get_info('catalyst');
  if (empty($entity_info['bundles'])) return;

  catalyst_include('eck');
  catalyst_eck__entity_menu_alter($menu_items);
  catalyst_eck__bundle_menu_alter($menu_items);
  catalyst_eck__entity_type_menu_alter($menu_items);

  foreach ($entity_info['bundles'] AS $bundle => $bundle_info) {
    if (!empty($bundle_info['crud']['add']['path'])) {
      $path = $bundle_info['crud']['add']['path'];
      if (!empty($menu_items[$path])) {
        $menu_items[$path]['page callback'] = 'catalyst_entity_add';
      }
    }
    if (!empty($bundle_info['crud']['edit']['path'])) {
      $path = $bundle_info['crud']['edit']['path'];
      if (!empty($menu_items[$path])) {
        $menu_items[$path]['page callback'] = 'catalyst_entity_edit';
      }
    }
  }

  catalyst_include('plugins');
  catalyst_invoke_alter_all('hook menu alter', $menu_items);
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Make the field ui more usable by removing catalyst fields from none
 * catalyst entities.
 */
function catalyst_core_form_field_ui_field_overview_form_alter(&$form, &$form_state) {
  if ($form['#entity_type'] != 'catalyst')  {
    // After build callback in catalyst_core/includes/uncommoon.inc
    catalyst_form_load_include($form_state, 'uncommon');
    // Make any alterations as late as possible
    $form['#after_build'][] = 'catalyst_field_ui_field_overview_form_after_build';
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Hide catalyst specific input formats (prefixed with catalyst_).
 *
 * These input formats are revealed when catalyst_devel is enabled.
 */
function catalyst_core_form_filter_admin_overview_alter(&$form, &$form_state) {
  // The theme function doesn't check access to the element so hiding the
  // relevant filters is insufficient. Collect catalyst formats in a separate
  // element where they will be completely hidden.
  $form['catalyst_formats'] = array('#access' => FALSE);
  // Maintain the weight for consistency
  $weight = 0;
  foreach (element_children($form['formats']) AS $id) {
    $form['formats'][$id]['#weight'] = $weight++;
    if (strpos($id, 'catalyst_') === 0) {
      $form['catalyst_formats'][$id] = $form['formats'][$id];
      unset($form['formats'][$id]);
    }
  }
}


/**
 * Call back for the local action add (It adds a new entity).
 *
 * @param string $entity_type_name
 *   Entity type.
 * @param string $bundle_name
 *   Bundle.
 */
function catalyst_entity_add($entity_type_name, $bundle_name) {
  $entity_type = entity_type_load($entity_type_name);
  $bundle = bundle_load($entity_type_name, $bundle_name);

  $entity = entity_create($entity_type->name, array('type' => $bundle->name));
  return drupal_get_form("catalyst_entity_form_add_{$entity_type_name}_{$bundle_name}", $entity);
}

/**
 * Callback function for an entities edit page.
 *
 * @param string $entity_type_name
 *   Entity type.
 * @param string $bundle_name
 *   Bundle.
 * @param int $id
 *   the Id of the entity to be edited.
 */
function catalyst_entity_edit($entity_type_name, $bundle_name, $id) {
  if (is_numeric($id)) {
    $entity = entity_load_single($entity_type_name, $id);
  }
  elseif (is_object($id) and $id->entityType() === $entity_type_name) {
    $entity = $id;
  }

  return drupal_get_form("catalyst_entity_form_edit_{$entity_type_name}_{$bundle_name}", $entity);
}

/**
 * Implements hook_forms().
 */
function catalyst_core_forms($form_id, $args) {
  $forms = array();
  if (strpos($form_id, 'catalyst_entity_form_') === 0) {
    $forms[$form_id] = array(
      'callback' => 'catalyst_entity_form',
    );
  }
  return $forms;
}

/**
 * Catalyst entity form callback.
 *
 * @see catalyst_core_entity_info_alter().
 */
function catalyst_entity_form($form, &$form_state, $entity) {
  $form['entity'] = array(
    '#type' => 'value',
    '#value' => $entity,
  );
  $form['#entity_type'] = array(
    '#type' => 'value',
    '#value' => $entity->type,
  );

  $form_state[$entity->entityType()] = $entity;

  // Property Widget Handling through property_info by entity api.
  $property_info = entity_get_property_info($entity->entityType());
  $properties = array();
  $found_widget = FALSE;
  foreach ($property_info['properties'] as $pname => $pi) {
    if (array_key_exists('widget', $pi)) {
      $widget_callback = $pi['widget'];
      $widget = $widget_callback($entity);
      $properties[$pname] = $widget_callback;
      $form[$pname] = $widget_callback($entity);
      $found_widget = TRUE;
    }
  }

  if (!$found_widget) {
    // If there was no widget given through the property_info array, we look for
    // a widget in the property behaviors implemented.
    $entity_type = $entity->entityType();
    $entity_type = EntityType::loadByName($entity_type);

    $vars = array('entity' => $entity);
    $vars += $property_info;

    $widgets = eck_property_behavior_invoke_plugin($entity_type, 'default_widget', $vars);

    foreach ($widgets as $property => $widget) {
      $form[$property] = $widget;
    }
  }

  $form['actions'] = array('#type' => 'actions');
  $form['actions']['submit'] = array(
    '#type' => 'submit',
    '#weight' => 10000,
    '#value' => t('Save'),
  );

  // Entity Translation module integration.
  $langcode = LANGUAGE_NONE;
  if (module_exists('entity_translation') &&
    entity_translation_enabled($entity->entityType())) {
    $handler = entity_translation_get_handler($entity->entityType(), $entity);
    $langcode = $handler->getFormLanguage();
  }


  field_attach_form($entity->entityType(), $entity, $form, $form_state, $langcode);

  if (!isset($form_state['handler'])) {
    $form_state['handler'] = $entity->handler();
  }
  $handler = $form_state['handler'];
  if ($func = ctools_plugin_get_function($handler, 'entity form')) {
    $func($form, $form_state, $entity, $handler);
  }
  foreach ($handler['plugins'] AS $plugin_name => $plugin) {
    if ($func = ctools_plugin_get_function($plugin, 'entity form')) {
      $func($form, $form_state, $entity, $plugin, $handler);
    }
  }
  return $form;
}

/**
 * Validation function for entity form for validating the fields.
 */
function catalyst_entity_form_validate($form, &$state) {
  $entity = $state['values']['entity'];
  field_attach_form_validate($entity->entityType(), $entity, $form, $state);
}

/**
 * Submit function for entity form.
 */
function catalyst_entity_form_submit($form, &$state) {
  module_load_include('inc', 'eck', 'eck.entity');
  eck__entity__form_submit($form, $state);
}

/**
 * Implements hook_form_alter().
 */
function catalyst_core_form_alter(&$form, &$form_state, $form_id) {
  if (strpos($form_id, 'catalyst_entity_form_edit_') === 0 || strpos($form_id, 'catalyst_entity_form_add_') === 0) {
    catalyst_include('plugins');
    $handler = $form_state['handler'];
    if ($func = ctools_plugin_get_function($handler, 'entity form alter')) {
      $func($form, $form_state, $handler);
    }
    foreach ($handler['plugins'] AS $plugin_name => $plugin) {
      if ($func = ctools_plugin_get_function($plugin, 'entity form alter')) {
        $func($form, $form_state, $plugin, $handler);
      }
    }
  }
  if (isset($form['#catalyst_form']) && !empty($form['#catalyst_form'])) {
    //if (!isset($form['#process'])) $form['#process'] = array();
    //array_unshift($form['#process'], 'catalyst_form_process');
    $source = $form['#catalyst_form']['source'];
    $item = catalyst_load_single($source['type'], $source['machine']);
    if (isset($item->assets['preprocess.php'])) {
      $path = str_replace(drupal_realpath(DRUPAL_ROOT).'/', '', $item->assets['preprocess.php']->filepath);
      $form_state['build_info']['files']['catalyst_preprocess'] = $path;
    }
  }
  //catalyst_include('plugins');
  //catalyst_invoke_alter_all('hook form alter', $form, $form_state, $form_id);
}

function catalyst_form($form, $bundle, $machine, $vars = array()) {
  $form['#catalyst_form'] = array(
    'vars' => $vars,
    'source' => array(
      'type' => $bundle,
      'machine' => $machine,
    ),
  );
  return $form;
}

/**
 *
 */
function catalyst_form_process($form, &$form_state) {
  if (!function_exists($form_state['build_info']['form_id'])) {
    $source = $form['#catalyst_form']['source'];
    //if ($preprocess_php = entity_valval($item['wrapper']->field__preprocess)) {
    //  catalyst_eval($preprocess_php, $form['#catalyst_form']['vars']);
    //}
  }
  return $form;
}

/**
 * Shortcut function to include common catalyst files.
 */
function catalyst_include($name, $module = 'core') {
  require_once catalyst_get_path(sprintf('includes/%s.inc', $name), $module);
}

function catalyst_form_load_include(&$form_state, $name, $module = 'core') {
  return form_load_include($form_state, 'inc', 'catalyst_' . $module, 'includes/'. $name);
}

function catalyst_get_path($subpath = NULL, $module = 'core') {
  $path = drupal_get_path('module', 'catalyst_'. $module);
  if ($subpath) $path = sprintf('%s/%s', $path, $subpath);
  return $path;
}

/**
 * Helper function for array_merge().
 *
 * Merges all (array) arguments into the first argument which is a reference.
 *
 * Usage:
 * @code
 * catalyst_array_merge($array1, $array2, $array3);
 * @endcode
 *
 * @param array $result
 *   The base array of the merge whose reference will be merged into.
 *
 * @return array
 *   Returns the merged result array.
 */
function catalyst_array_merge(&$result) {
  $arrArgs = func_get_args();
  array_shift($arrArgs);
  $result = is_null($result) ? array() : (array)$result;
  while ($array = array_shift($arrArgs)) {
    $array = is_null($array) ? array() : (array)$array;
    $result = array_merge($result, $array);
  }
  return $result;
}

/**
 * @see eck__entity_access().
 */
function catalyst_entity_access_strict($op) {
  if ($op == 'view') {
    $args = func_get_args();
    return call_user_func_array('eck__entity_access', $args);
  }
  return FALSE;
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Hide Catalyst features from the features admin list.
 *
 * Note: Catalyst features will be exposed when catalyst_devel is installed.
 */
function catalyst_core_form_features_admin_form_alter(&$form, &$form_state) {
  if (!module_exists('catalyst_admin')) {
    $form['package_catalyst']['#access'] = FALSE;
  }
}

/**
 *
 */
function catalyst_menu_item_disable(&$menu_item) {
  if ($menu_item['access callback'] !== FALSE) {
    $menu_item['access callback original'] = $menu_item['access callback'];
    $menu_item['access callback'] = FALSE;
  }
}

function catalyst_menu_item_restore(&$menu_item) {
  if ($menu_item['access callback'] === FALSE) {
    $menu_item['access callback'] = $menu_item['access callback original'];
    unset($menu_item['access callback original']);
  }
}

function catalyst_set_realm_site_action($entity, $context) {
  $entity->wrapper()->field__internal->set(FALSE);
}

function catalyst_set_realm_system_action($entity, $context) {
  $entity->wrapper()->field__internal->set(TRUE);
}

function catalyst_update_package_action_form($context) {
  catalyst_include('actions');
  $context['entity_type'] = 'catalyst';
  return catalyst_update_package_form($context);
}
function catalyst_update_package_action_submit($form, $form_state) {
  catalyst_include('actions');
  return catalyst_update_package_form_submit($form, $form_state);
}
function catalyst_update_package_action($entity, $context) {
  catalyst_include('actions');
  catalyst_update_package($entity, $context);
}

function catalyst_menu_access_callback($entity_type, $entity_id) {
  if ($entity = entity_load_single($entity_type, $entity_id)) {
    $menu = entity_valval($entity->wrapper()->field__menu);
    if ($accessphp = entity_valval($entity->wrapper()->field__access)) {
      $variables = array();
      $exportvars = catalyst_menu_parse_path($menu['path']);
      return (boolean) catalyst_eval($accessphp, $variables, $exportvars);
    }
  }
  return FALSE;
}

function catalyst_menu_title_callback($entity_type, $entity_id) {
  $entity = entity_load_single($entity_type, $entity_id);
  $menu_options = entity_valval($entity->wrapper()->field__menu);
  $variables = catalyst_menu_parse_path($menu_options['path']);
  $key = implode(':', array(
    $entity->wrapper()->type(),
    $entity->wrapper()->getBundle(),
    $entity->wrapper()->getIdentifier(),
    'menu_title',
  ));
  catalyst_include('twig');
  return catalyst_twig_render($menu_options['menu']['title'], $variables, $key);
}

function catalyst_menu_parent_title_callback($entity_type, $entity_id) {
  $entity = entity_load_single($entity_type, $entity_id);
  $menu_options = entity_valval($entity->wrapper()->field__menu);
  $variables = catalyst_menu_parse_path($menu_options['path']);
  $key = implode(':', array(
    $entity->wrapper()->type(),
    $entity->wrapper()->getBundle(),
    $entity->wrapper()->getIdentifier(),
    'parent_menu_title',
  ));
  catalyst_include('twig');
  return catalyst_twig_render($menu_options['menu']['parent']['title'], $variables, $key);
}

function catalyst_menu_page_callback($entity_type, $entity_id) {
  $entity = entity_load_single($entity_type, $entity_id);
  return $entity->display(TRUE);
}

function catalyst_menu_parse_path($path) {
  $return = array();
  $parts = explode('/', $path);
  foreach ($parts AS $i => $part) {
    if (strpos($part, '%') === 0) {
      $name = substr($part, 1);
      $loader = $name . '_load';
      if (function_exists($loader) && $loadId = arg($i)) {
        $return[$name] = $loader($loadId);
      }
    }
    elseif (strpos($part, '@') === 0) {
      $name = substr($part, 1);
      $return[$name] = NULL;
      if (arg($i)) {
        $return[$name] = arg($i);
      }
    }
  }
  return $return;
}

function catalyst_lookup_entity($type, $machine, $refresh = FALSE) {
  $entry = catalyst_registry_entry($type, $machine, $refresh);
  return $entry && !empty($entry->id) ? $entry->id : NULL;
}

function catalyst_entity_map() {
  $map = &drupal_static(__FUNCTION__);
  if (!isset($map)) {
    $result = db_query("SELECT entity_type, bundle, entity_id, field__machine_machine AS machine FROM {field_data_field__machine}");
    foreach ($result AS $item) {
      if (!isset($map[$item->entity_type])) {
        $map[$item->entity_type] = array();
      }
      if (!isset($map[$item->entity_type][$item->bundle])) {
        $map[$item->entity_type][$item->bundle] = array();
      }
      $map[$item->entity_type][$item->bundle][$item->machine] = $item->entity_id;
    }
  }
  return $map;
}

/**
 *
 * @code
 * Load all entities of one type.
 * catalyst_load('block');
 *
 * Load multiple entities by numeric db id.
 * Depends on the first parameter being a numeric (non-associative) array with
 * integer values.
 * catalyst_load(array(1, 2, 3), TRUE);
 *
 * Load multiple entities by machine name.
 * Depends on the second parameter being a numeric (non-associative) array with
 * string values.
 * catalyst_load('block', array('block_1', 'block_2'));
 *
 * Load multiple entities by conditions.
 * Depends on the second parameter being an ASSOCIATIVE array.
 * catalyst_load('block', array('filter1' => 1));
 * @endcode
 */
function catalyst_load($a0) {
  $arg = func_get_args();
  if (is_array($a0)) {
    $refresh = isset($arg[1]) ? $arg[1] : FALSE;
    $entities = entity_load('catalyst', $a0, array(), $refresh);
  }
  else {
    $type = $a0;
    if (!isset($arg[1]) || !is_array($arg[1])) {
      $query = new EntityFieldQuery();
      $result = $query->entityCondition('entity_type', 'catalyst', '=')
        ->propertyCondition('type', $type, '=')
        ->execute();
      $entities = entity_load('catalyst', array_keys($result['catalyst']), array(), isset($arg[1]) && $arg[1]);
    }
    else {
      $keys = array_keys($arg[1]);
      $refresh = isset($arg[2]) && $arg[2];
      $ids = array();
      if (is_numeric($keys[0])) {
        foreach ($arg[1] AS $mxd) {
          if (is_numeric($mxd)) {
            $ids[] = (int)$mxd;
          }
          else if ($id = catalyst_lookup_entity($type, $mxd)) {
            $ids[] = $id;
          }
        }
        if ($ids) {
          $entities = entity_load('catalyst', $ids, array(), $refresh);
        }
        else return array();
      }
      else {
        $entities = entity_load('catalyst', NULL, $conditions, $refresh);
      }
    }
  }
  $return = array();
  foreach ($entities AS $key => $entity) {
    $entry = catalyst_registry_entry($entity->type, $entity->machine);
    $entry->machine = $entity->machine;
    $entry->type = $entity->type;
    $entry->entity = $entity;
    $entry->wrapper = entity_metadata_wrapper('catalyst', $entity);
    $return[$key] = $entry;
  }
  return $return;
}

/**
 * @code
 * Load by machine name (with optional refresh option):
 * catalyst_load_single('block', 'my_block', TRUE);
 *
 * Load by entity id (with optional refresh option):
 * catalyst_load_single(133);
 *
 * @endcode
 */
function catalyst_load_single($a0) {
  $arg = func_get_args();
  if (count($arg) < 1) {
    throw new Exception('Invalid parameteres in '.__function__);
  }
  else if (is_numeric($arg[0])) {
    $id = $arg[0];
    $refresh = isset($arg[1]) ? $arg[1] : FALSE;
    $entities = catalyst_load(array($id), $refresh);
  }
  else {
    $id = $arg[1];
    $refresh = isset($arg[2]) ? $arg[2] : FALSE;
    $entities = catalyst_load($arg[0], array($id), $refresh);
  }
  return array_shift($entities);
}

/**
 * Implements hook_entity_update().
 */
function catalyst_core_entity_update($entity, $entity_type) {
  catalyst_include('plugins');
  if ($entity instanceof CatalystEntity) {
    catalyst_registry_needs_rebuild();
    //catalyst_invoke_all('catalyst entity update', $entity, $entity_type);
  }
  //catalyst_invoke_all('hook entity update', $entity, $entity_type);
}

/**
 * Implements hook_entity_delete().
 */
function catalyst_core_entity_delete($entity, $entity_type) {
  catalyst_include('plugins');
  if ($entity instanceof CatalystEntity) {
    catalyst_registry_needs_rebuild();
    //catalyst_invoke_all('catalyst entity delete', $entity, $entity_type);
    catalyst_include('code');
    catalyst_code_entity_delete($entity);
  }
  //catalyst_invoke_all('hook entity delete', $entity, $entity_type);
}

/**
 * Implements hook_entity_insert().
 */
function catalyst_core_entity_insert($entity, $entity_type) {
  catalyst_include('plugins');
  if ($entity instanceof CatalystEntity) {
    catalyst_registry_needs_rebuild();
    catalyst_invoke_all('catalyst entity insert', $entity, $entity_type);
  }
  catalyst_invoke_all('hook entity insert', $entity, $entity_type);
}

/**
 * Returns catalyst fields that are *safe* for other entity types.
 */
function catalyst_safe_fields() {
  $fields = module_invoke_all(__FUNCTION__);
  $fields[] = 'field__js';
  $fields[] = 'field__css';
  drupal_alter(__FUNCTION__, $fields);
  return $fields;
}

/**
 * Resolve a field to it's type.
 *
 * @param
 */
function catalyst_resolve_field($field_name_abbr, $bundle, $entity_type = 'catalyst') {
  static $cache;
  if (!isset($cache)) $cache = array();
  if (!isset($cache[$entity_type])) $cache[$entity_type] = array();
  if (!isset($cache[$entity_type][$bundle])) $cache[$entity_type][$bundle] = array();
  $field_name_abbr = str_replace('field__', '', $field_name_abbr);
  if (!isset($cache[$entity_type][$bundle][$field_name_abbr])) {
    $suffixes = array($field_name_abbr);
    switch ($field_name_abbr) {
      case 'css':
      case 'js':
      case 'media_stylesheets':
      case 'media_javascripts':
        array_push($suffixes, $field_name_abbr . '__layout', $field_name_abbr . '__page');
        break;
      case 'blockplacements':
        $suffixes = array(
          $field_name_abbr . '__block',
          $field_name_abbr . '__layout',
          $field_name_abbr . '__layfield',
        );
        break;
    }
    $instances = field_info_instances($entity_type, $bundle);
    $result = FALSE;
    foreach ($suffixes AS $suffix) {
      $field_name = 'field__' . $suffix;
      if (isset($instances[$field_name])) {
        $result = $instances[$field_name];
        if (!empty($result['settings']['better_formats']['allowed_formats'])) {
          $formats = array_keys(array_filter($result['settings']['better_formats']['allowed_formats']));
          $result['format'] = array_pop($formats);
        }
        break;
      }
    }
    $cache[$entity_type][$bundle][$field_name_abbr] = $result;
  }
  return $cache[$entity_type][$bundle][$field_name_abbr];
}

/**
 * Workaround for this issue with entity_metadata_wrapper:
 * https://www.drupal.org/node/1596594
 *
 * @code
 * $entity = entity_load_single('user', 1);
 * $myfield_value = entity_valval($entity->wraper()->field_myfield);
 * @endcode
 *
 * @param $data
 *   An EntityStructureWrapper
 * @return
 *   The value of the $data's value object's value attribute.
 */
function entity_valval(EntityStructureWrapper $data) {
  if ($data->value()) {
    return $data->value->value();
  }
}

/**
 *
 * @param $code string
 *   A string of php code without opening and closing tags.
 *
 * @param $variables array
 *   An array of variables that the $code is able to modify. $variables are
 *   intended for a template.
 * @return NULL or boolean
 *   Evaluations with catalyst_eval() must return null or boolean. Code
 *   processed by catalyst_eval() should never return a string. An exception
 *   will be thrown anticipating a syntax error when a string is returned.
 * @param array $___exportvars
 *   Array of "non-$variables" variables that the code cannot modify. Export
 *   vars are accessible at the top-level of evaluations, but are not
 *   passed on to templates (but can be manually in preprocessing).
 *
 * @todo Improve exception error message/handling for better debugging.
 */
function catalyst_eval($code, &$variables, $___exportvars = array()) {
  extract($___exportvars);
  unset($___exportvars);
  ob_start();
  $result = eval($code);
  $output = ob_get_contents();
  ob_end_clean();
  if (!in_array($result, array(NULL, TRUE, FALSE, 0, 1))) {
    throw new Exception($output);
  }
  return $result;
}
