<?php
/**
 * @file
 * Code for the Catalyst Core feature.
 */

include_once 'catalyst_core.features.inc';
include_once 'common/registry.inc';

define('CATALYST_CSS_SYSTEM', -101);
define('CATALYST_CSS_LAYOUT', 101);
define('CATALYST_CSS_PAGE', 201);
define('CATALYST_CSS_OTHER', 301);

define('CATALYST_JS_SYSTEM', -201);
define('CATALYST_JS_LIBRARY', -101);
define('CATALYST_JS_LAYOUT', 101);
define('CATALYST_JS_PAGE', 201);
define('CATALYST_JS_OTHER', 301);

/**
 * Implements hook_ctools_plugin_directory().
 */
function catalyst_core_ctools_plugin_directory($owner, $plugin_type) {
  if ($owner == 'catalyst') {
    if ($plugin_type == 'plugin') return 'plugins/catalyst';
    return 'plugins/'. $plugin_type;
  }
}

/**
 * Implements hook_theme().
 */
function catalyst_core_theme() {
  catalyst_include('plugins');
  $return = catalyst_invoke_all('theme');
  $return['catalyst_menu_widget_menu_options'] = array(
    'render element' => 'element',
    'template' => 'catalyst-menu-widget-menu-options',
    'path' => catalyst_get_path() . '/theme',
  );
  return $return;
}

/**
 * Implements hook_catalyst_twig_render_alter().
 */
function catalyst_core_catalyst_twig_render_alter(&$twig, &$variables, $key = NULL) {
  $twig->addFunction(new Twig_SimpleFunction('coreblock', 'catalyst_coreblock'));
  $twig->addFunction(new Twig_SimpleFunction('form', 'catalyst_twigform'));
  $twig->addFunction(new Twig_SimpleFunction('entity_uri', 'entity_uri'));
  $twig->addFilter(new Twig_SimpleFilter('entity_valval', 'catalyst_twig_entity_valval'));
}

function catalyst_twig_entity_valval($data) {
  if ($data) return entity_valval($data);
}

function catalyst_twigform($callback) {
  $args = func_get_args();
  $form = call_user_func_array('drupal_get_form', $args);
  return render($form);
}


/**
 * Implements hook_action_info().
 */
function catalyst_core_action_info() {
  return array(
    'catalyst_update_package_action' => array(
      'type' => 'catalyst',
      'label' => t('Set or change package'),
      'configurable' => TRUE,
      'triggers' => array('any'),
    ),
    'catalyst_set_realm_system_action' => array(
      'type' => 'catalyst',
      'label' => t('Send to system realm'),
      'configurable' => FALSE,
      'triggers' => array('any'),
    ),
    'catalyst_set_realm_site_action' => array(
      'type' => 'catalyst',
      'label' => t('Send to site realm'),
      'configurable' => FALSE,
      'triggers' => array('any'),
    ),
  );
}

/**
 * Implements hook_entity_info_alter().
 */
function catalyst_entity_info_alter(&$entity_info) {
  $entity_info['catalyst']['entity keys'] += array(
    'name' => 'name',
    'module' => 'module',
  );
  $entity_info['catalyst']['access callback'] = 'catalyst_entity_access_strict';
  $entity_info['catalyst']['entity class'] = 'CatalystEntity';
  // Restrict view modes on catalyst entities and add the "template" view
  // mode for the rendering of (some) templates
  $entity_info['catalyst']['view modes'] = array(
    'full' => array(
      'label' => 'Full',
      'custom settings' => FALSE,
    ),
    'template' => array(
      'label' => 'Template',
      'custom settings' => TRUE,
    ),
  );
}

/**
 * Get info about catalyst types.
 */
function catalyst_get_plugin_info($plugin = NULL, $reset = NULL) {
  $stored_info = &drupal_static(__FUNCTION__);
  if ($reset || !isset($stored_info)) {
    foreach (module_implements('catalyst_plugin_info') AS $module) {
      foreach (module_invoke($module, 'catalyst_plugin_info') as $type => $info) {
        $stored_info[$type] = $info + array(
          'module' => $module,
          'exportables' => FALSE,
        );
      }
    }
    drupal_alter('catalyst_plugin_info', $stored_info);
  }
  if ($plugin) {
    return isset($stored_info[$plugin]) ? $stored_info[$plugin] : FALSE;
  }
  return $stored_info;
}

/**
 * Implements hook_hook_info().
 */
function catalyst_core_hook_info() {
  $group = array('group' => 'catalyst');
  // Layout hooks
  $hooks['catalyst_layout_alter'] = $group;
  // Plugin hooks
  $hooks['catalyst_plugin_info'] = $group;
  $hooks['catalyst_plugin_info_alter'] = $group;
  // Export hooks
  $hooks['catalyst_export_dependencies'] = $group;
  $hooks['catalyst_export_candidates'] = $group;
  $hooks['catalyst_prepare_export'] = $group;
  $hooks['catalyst_export_alter'] = $group;
  // Menu hooks
  $hooks['catalyst_ignore_menus'] = $group;
  $hooks['catalyst_ignore_menus_alter'] = $group;
  // Twig
  $hooks['catalyst_twig_render_alter'] = $group;
  // Fields, entities, and node related hooks
  $hooks['catalyst_node_types'] = $group;
  $hooks['catalyst_safe_fields'] = $group;
  $hooks['catalyst_import_alter'] = $group;
  $hooks['catalyst_export_metadata'] = $group;
  $hooks['catalyst_export_component'] = $group;
  $hooks['catalyst_registry_alter'] = $group;
  return $hooks;
}

/**
 * Implements hook_menu_alter().
 */
function catalyst_core_menu_alter(&$menu_items) {
  $path = 'admin/reports/fields';
  if (isset($menu_items[$path])) {
    $menu_items[$path] = array_merge($menu_items[$path], array(
      'page callback' => 'catalyst_field_ui_clean_field_list',
      'file path' => catalyst_get_path() . '/includes',
      'module' => 'catalyst_core',
      'file' => 'fields.inc',
    ));
  }
  catalyst_include('eck');
  catalyst_eck__entity_menu_alter($menu_items);
  catalyst_eck__bundle_menu_alter($menu_items);
  catalyst_eck__entity_type_menu_alter($menu_items);
  catalyst_include('menu_widget');
  if (variable_get('install_task', 'done') != 'install_system_module') {
    catalyst_menu_widget_menu_alter($menu_items);
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Make the field ui more usable by removing catalyst fields from none
 * catalyst entities.
 */
function catalyst_core_form_field_ui_field_overview_form_alter(&$form, &$form_state) {
  if ($form['#entity_type'] != 'catalyst')  {
    // After build callback in catalyst_core/includes/uncommoon.inc
    catalyst_form_load_include($form_state, 'uncommon');
    // Make any alterations as late as possible
    $form['#after_build'][] = 'catalyst_field_ui_field_overview_form_after_build';
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Hide catalyst specific input formats (prefixed with catalyst_).
 *
 * These input formats are revealed when catalyst_devel is enabled.
 */
function catalyst_core_form_filter_admin_overview_alter(&$form, &$form_state) {
  // The theme function doesn't check access to the element so hiding the
  // relevant filters is insufficient. Collect catalyst formats in a separate
  // element where they will be completely hidden.
  $form['catalyst_formats'] = array('#access' => FALSE);
  // Maintain the weight for consistency
  $weight = 0;
  foreach (element_children($form['formats']) AS $id) {
    $form['formats'][$id]['#weight'] = $weight++;
    if (strpos($id, 'catalyst_') === 0) {
      $form['catalyst_formats'][$id] = $form['formats'][$id];
      unset($form['formats'][$id]);
    }
  }
}

function catalyst_form($form, $bundle, $machine, $vars = array()) {
  $form['#catalyst_form'] = array(
    'vars' => $vars,
    'source' => array(
      'type' => $bundle,
      'machine' => $machine,
    ),
  );
  return $form;
}

/**
 * Implements hook_form_alter().
 */
function catalyst_core_form_alter(&$form, &$form_state, $form_id) {
  if (strpos($form_id, 'eck__entity__form_edit_') === 0 || strpos($form_id, 'eck__entity__form_add_') === 0) {
    $plugins = ctools_get_plugins('catalyst', 'plugin');
    foreach ($plugins AS $plugin) {
      if ($func = ctools_plugin_get_function($plugin, 'entity form')) {
        $func($form, $form_state);
      }
    }
  }
  if (isset($form['#catalyst_form']) && !empty($form['#catalyst_form'])) {
    //if (!isset($form['#process'])) $form['#process'] = array();
    //array_unshift($form['#process'], 'catalyst_form_process');
    $source = $form['#catalyst_form']['source'];
    $item = catalyst_load_single($source['type'], $source['machine']);
    if (isset($item->assets['preprocess.php'])) {
      $path = str_replace(drupal_realpath(DRUPAL_ROOT).'/', '', $item->assets['preprocess.php']->filepath);
      $form_state['build_info']['files']['catalyst_preprocess'] = $path;
    }
  }
  if (isset($form['field__menu'])) {
    catalyst_form_load_include($form_state, 'menu_widget');
    catalyst_menu_widget_form_alter($form, $form_state);
  }
  if (isset($form['field__data']) && $form['#bundle'] == 'package') {
    catalyst_form_load_include($form_state, 'package_form_alter');
    catalyst_package_form_alter($form, $form_state);
  }
}

/**
 *
 */
function catalyst_form_process($form, &$form_state) {
  if (!function_exists($form_state['build_info']['form_id'])) {
    $source = $form['#catalyst_form']['source'];
    //if ($preprocess_php = entity_valval($item['wrapper']->field__preprocess)) {
    //  catalyst_eval($preprocess_php, $form['#catalyst_form']['vars']);
    //}
  }
  return $form;
}

/**
 * Shortcut function to include common catalyst files.
 */
function catalyst_include($name, $module = 'core') {
  require_once drupal_get_path('module', 'catalyst_' . $module) . '/includes/' . $name . '.inc';
}

function catalyst_form_load_include(&$form_state, $name, $module = 'core') {
  return form_load_include($form_state, 'inc', 'catalyst_' . $module, 'includes/'. $name);
}

function catalyst_get_path($module = 'core') {
  return drupal_get_path('module', 'catalyst_'. $module);
}

function catalyst_node_types() {
  return array();
}

function catalyst_entity_is_a($bundle, $entity, $entity_type = 'catalyst', $bundle_key = 'type') {
  switch (true) {
    // Compare the entity type if one is provided
    case isset($entity->entity_type) && $entity->entity_type != $entity_type:
    // Compare the bundle
    case !isset($entity->{$bundle_key}) || $entity->{$bundle_key} != $bundle:
      return FALSE;
  }
  return TRUE;
}

function catalyst_entity_is_new($entity) {
  return isset($entity->is_new) && $entity->is_new;
}

/**
 * Helper function for array_merge().
 *
 * Merges all (array) arguments into the first argument which is a reference.
 *
 * Usage:
 * @code
 * catalyst_array_merge($array1, $array2, $array3);
 * @endcode
 *
 * @param array $result
 *   The base array of the merge whose reference will be merged into.
 *
 * @return array
 *   Returns the merged result array.
 */
function catalyst_array_merge(&$result) {
  $arrArgs = func_get_args();
  array_shift($arrArgs);
  $result = is_null($result) ? array() : (array)$result;
  while ($array = array_shift($arrArgs)) {
    $array = is_null($array) ? array() : (array)$array;
    $result = array_merge($result, $array);
  }
  return $result;
}

/**
 * @see eck__entity_access().
 */
function catalyst_entity_access_strict($op) {
  if ($op == 'view') {
    $args = func_get_args();
    return call_user_func_array('eck__entity_access', $args);
  }
  return FALSE;
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Hide Catalyst features from the features admin list.
 *
 * Note: Catalyst features will be exposed when catalyst_devel is installed.
 */
function catalyst_core_form_features_admin_form_alter(&$form, &$form_state) {
  $form['package_catalyst']['#access'] = FALSE;
}

/**
 *
 */
function catalyst_menu_item_disable(&$menu_item) {
  if ($menu_item['access callback'] !== FALSE) {
    $menu_item['access callback original'] = $menu_item['access callback'];
    $menu_item['access callback'] = FALSE;
  }
}

function catalyst_menu_item_restore(&$menu_item) {
  if ($menu_item['access callback'] === FALSE) {
    $menu_item['access callback'] = $menu_item['access callback original'];
    unset($menu_item['access callback original']);
  }
}

function catalyst_set_realm_site_action($entity, $context) {
  $wrapper = entity_metadata_wrapper('catalyst', $entity);
  $wrapper->field__internal->set(FALSE);
}

function catalyst_set_realm_system_action($entity, $context) {
  $wrapper = entity_metadata_wrapper('catalyst', $entity);
  $wrapper->field__internal->set(TRUE);
}

function catalyst_update_package_action_form($context) {
  catalyst_include('actions');
  $context['entity_type'] = 'catalyst';
  return catalyst_update_package_form($context);
}
function catalyst_update_package_action_submit($form, $form_state) {
  catalyst_include('actions');
  return catalyst_update_package_form_submit($form, $form_state);
}
function catalyst_update_package_action($entity, $context) {
  catalyst_include('actions');
  catalyst_update_package($entity, $context);
}

function catalyst_render_block($module, $delta = '') {
  $block = block_load($module, $delta);
  $build = _block_get_renderable_array(_block_render_blocks(array($block)));
  return render($build);
}

function catalyst_menu_access_callback($entity_type, $entity_id) {
  if ($entity = entity_load_single($entity_type, $entity_id)) {
    $wrapper = entity_metadata_wrapper($entity_type, $entity);
    $menu = entity_valval($wrapper->field__menu);
    if ($accessphp = entity_valval($wrapper->field__access)) {
      $variables = array();
      $exportvars = catalyst_menu_parse_path($menu['path']);
      return (boolean) catalyst_eval($accessphp, $variables, $exportvars);
    }
  }
  return FALSE;
}

function catalyst_menu_title_callback($entity_type, $entity_id) {
  $entity = entity_load_single($entity_type, $entity_id);
  $wrapper = entity_metadata_wrapper($entity_type, $entity);
  $menu_options = entity_valval($wrapper->field__menu);
  $variables = catalyst_menu_parse_path($menu_options['path']);
  $key = implode(':', array(
    $wrapper->type(),
    $wrapper->getBundle(),
    $wrapper->getIdentifier(),
    'menu_title',
  ));
  catalyst_include('twig');
  return catalyst_twig_render($menu_options['menu']['title'], $variables, $key);
}

function catalyst_menu_parent_title_callback($entity_type, $entity_id) {
  $entity = entity_load_single($entity_type, $entity_id);
  $wrapper = entity_metadata_wrapper($entity_type, $entity);
  $menu_options = entity_valval($wrapper->field__menu);
  $variables = catalyst_menu_parse_path($menu_options['path']);
  $key = implode(':', array(
    $wrapper->type(),
    $wrapper->getBundle(),
    $wrapper->getIdentifier(),
    'parent_menu_title',
  ));
  catalyst_include('twig');
  return catalyst_twig_render($menu_options['menu']['parent']['title'], $variables, $key);
}

function catalyst_menu_page_callback($entity_type, $entity_id) {
  $entity = entity_load_single($entity_type, $entity_id);
  return $entity->view('template', LANGUAGE_NONE, TRUE);
  module_load_include('entity.inc', 'eck');
  return eck__entity__view_callback(array($entity), 'template', $entity->wrapper()->language());
}

function catalyst_menu_parse_path($path) {
  $return = array();
  $parts = explode('/', $path);
  foreach ($parts AS $i => $part) {
    if (strpos($part, '%') === 0) {
      $name = substr($part, 1);
      $loader = $name . '_load';
      if (function_exists($loader) && $loadId = arg($i)) {
        $return[$name] = $loader($loadId);
      }
    }
    elseif (strpos($part, '@') === 0) {
      $name = substr($part, 1);
      $return[$name] = NULL;
      if (arg($i)) {
        $return[$name] = arg($i);
      }
    }
  }
  return $return;
}

function catalyst_coreblock($module, $delta = 0, $render = true) {
  if ($block = block_load($module, $delta)) {
    if (!isset($block->title)) $block->title = null;
    if (!isset($block->region)) $block->region = null;
    $build = _block_get_renderable_array(_block_render_blocks(array($block)));
    return $render ? drupal_render($build) : $build;
  }
  throw new Exception(t('Missing block %delta in %module', array(
    '%module' => $module,
    '%delta' => $delta,
  )));
}

function catalyst_lookup_entity($type, $machine, $refresh = FALSE) {
  $entry = catalyst_registry_entry($type, $machine, $refresh);
  return $entry && !empty($entry->id) ? $entry->id : NULL;
}

function catalyst_entity_map() {
  $map = &drupal_static(__FUNCTION__);
  if (!isset($map)) {
    $result = db_query("SELECT entity_type, bundle, entity_id, field__machine_machine AS machine FROM {field_data_field__machine}");
    foreach ($result AS $item) {
      if (!isset($map[$item->entity_type])) {
        $map[$item->entity_type] = array();
      }
      if (!isset($map[$item->entity_type][$item->bundle])) {
        $map[$item->entity_type][$item->bundle] = array();
      }
      $map[$item->entity_type][$item->bundle][$item->machine] = $item->entity_id;
    }
  }
  return $map;
}

/**
 *
 * @code
 * Load all entities of one type.
 * catalyst_load('block');
 *
 * Load multiple entities by numeric db id.
 * Depends on the first parameter being a numeric (non-associative) array with
 * integer values.
 * catalyst_load(array(1, 2, 3), TRUE);
 *
 * Load multiple entities by machine name.
 * Depends on the second parameter being a numeric (non-associative) array with
 * string values.
 * catalyst_load('block', array('block_1', 'block_2'));
 *
 * Load multiple entities by conditions.
 * Depends on the second parameter being an ASSOCIATIVE array.
 * catalyst_load('block', array('filter1' => 1));
 * @endcode
 */
function catalyst_load($a0) {
  $arg = func_get_args();
  if (is_array($a0)) {
    $refresh = isset($arg[1]) ? $arg[1] : FALSE;
    $entities = entity_load('catalyst', $a0, array(), $refresh);
  }
  else {
    $type = $a0;
    if (!isset($arg[1]) || !is_array($arg[1])) {
      $query = new EntityFieldQuery();
      $result = $query->entityCondition('entity_type', 'catalyst', '=')
        ->propertyCondition('type', $type, '=')
        ->execute();
      $entities = entity_load('catalyst', array_keys($result['catalyst']), array(), isset($arg[1]) && $arg[1]);
    }
    else {
      $keys = array_keys($arg[1]);
      $refresh = isset($arg[2]) && $arg[2];
      $ids = array();
      if (is_numeric($keys[0])) {
        foreach ($arg[1] AS $mxd) {
          if (is_numeric($mxd)) {
            $ids[] = (int)$mxd;
          }
          else if ($id = catalyst_lookup_entity($type, $mxd)) {
            $ids[] = $id;
          }
        }
        if ($ids) {
          $entities = entity_load('catalyst', $ids, array(), $refresh);
        }
        else return array();
      }
      else {
        $entities = entity_load('catalyst', NULL, $conditions, $refresh);
      }
    }
  }
  $return = array();
  foreach ($entities AS $key => $entity) {
    $entry = catalyst_registry_entry($entity->type, $entity->machine);
    $entry->machine = $entity->machine;
    $entry->type = $entity->type;
    $entry->entity = $entity;
    $entry->wrapper = entity_metadata_wrapper('catalyst', $entity);
    $return[$key] = $entry;
  }
  return $return;
}

/**
 * @code
 * Load by machine name (with optional refresh option):
 * catalyst_load_single('block', 'my_block', TRUE);
 *
 * Load by entity id (with optional refresh option):
 * catalyst_load_single(133);
 *
 * @endcode
 */
function catalyst_load_single($a0) {
  $arg = func_get_args();
  if (count($arg) < 1) {
    throw new Exception('Invalid parameteres in '.__function__);
  }
  else if (is_numeric($arg[0])) {
    $id = $arg[0];
    $refresh = isset($arg[1]) ? $arg[1] : FALSE;
    $entities = catalyst_load(array($id), $refresh);
  }
  else {
    $id = $arg[1];
    $refresh = isset($arg[2]) ? $arg[2] : FALSE;
    $entities = catalyst_load($arg[0], array($id), $refresh);
  }
  return array_shift($entities);
}

/**
 * Implements hook_entity_update().
 */
function catalyst_core_entity_update($entity, $type) {
  _catalyst_entity_change($entity, $type);
}

/**
 * Implements hook_entity_delete().
 */
function catalyst_core_entity_delete($entity, $type) {
  _catalyst_entity_change($entity, $type);
}

/**
 * Implements hook_entity_insert().
 */
function catalyst_core_entity_insert($entity, $type) {
  _catalyst_entity_change($entity, $type);
}

function _catalyst_entity_change($entity, $entity_type) {
  if ($entity_type == 'catalyst') {
    catalyst_registry_needs_rebuild();
    if ($field = catalyst_resolve_field('menu', $entity->type)) {
      variable_set('menu_rebuild_needed', TRUE);
    }
    catalyst_include('entity');
    foreach (array('js', 'css') AS $ext) {
      if ($field = catalyst_resolve_field('js', $entity->type)) {
        $fn = $field['field_name'];
        if (!empty($entity->{$fn}) && $value = entity_valval($entity->wrapper()->{$fn})) {
          $scope = str_replace(array('field__'.$ext,'__'), '', $fn);
          $fname = empty($scope) ? 'custom' : $scope;
          $filepath = catalyst_entity_get_public_filepath('catalyst', $entity, $fname.'.'.$ext);
          if (file_exists(drupal_realpath($filepath))) {
            drupal_unlink($filepath);
          }
          $build = field_view_field('catalyst', $entity, 'field__body', array('type' => 'catalyst_twig_formatter'));
          file_unmanaged_save_data(drupal_render($build), $filepath, FILE_EXISTS_REPLACE);
        }
      }
    }
  }
}

/**
 * Returns catalyst fields that are *safe* for other entity types.
 */
function catalyst_safe_fields() {
  $fields = module_invoke_all(__FUNCTION__);
  $fields[] = 'field__js';
  $fields[] = 'field__css';
  drupal_alter(__FUNCTION__, $fields);
  return $fields;
}

/**
 * Resolve a field to it's type.
 *
 * @param
 */
function catalyst_resolve_field($field_name_abbr, $bundle, $entity_type = 'catalyst') {
  static $cache;
  if (!isset($cache)) $cache = array();
  if (!isset($cache[$entity_type])) $cache[$entity_type] = array();
  if (!isset($cache[$entity_type][$bundle])) $cache[$entity_type][$bundle] = array();
  $field_name_abbr = str_replace('field__', '', $field_name_abbr);
  if (!isset($cache[$entity_type][$bundle][$field_name_abbr])) {
    $suffixes = array($field_name_abbr);
    switch ($field_name_abbr) {
      case 'css':
      case 'js':
      case 'media_stylesheets':
      case 'media_javascripts':
        array_push($suffixes, $field_name_abbr . '__layout', $field_name_abbr . '__page');
        break;
      case 'blockplacements':
        $suffixes = array(
          $field_name_abbr . '__block',
          $field_name_abbr . '__layout',
          $field_name_abbr . '__layfield',
        );
        break;
    }
    $instances = field_info_instances($entity_type, $bundle);
    $result = FALSE;
    foreach ($suffixes AS $suffix) {
      $field_name = 'field__' . $suffix;
      if (isset($instances[$field_name])) {
        $result = $instances[$field_name];
        if (!empty($result['settings']['better_formats']['allowed_formats'])) {
          $formats = array_keys(array_filter($result['settings']['better_formats']['allowed_formats']));
          $result['format'] = array_pop($formats);
        }
        break;
      }
    }
    $cache[$entity_type][$bundle][$field_name_abbr] = $result;
  }
  return $cache[$entity_type][$bundle][$field_name_abbr];
}

/**
 * Implements hook_field_formatter_info().
 */
function catalyst_core_field_formatter_info() {
  return array(
    'catalyst_twig_formatter' => array(
      'field types' => array('text_long'),
      'label' => t('Catalyst Twig Parser'),
    ),
    'catalyst_php_preprocess' => array(
      'field types' => array('text_long'),
      'label' => t('Catalyst PHP Preprocessing'),
    ),
    'catalyst_js_formatter' => array(
      'field types' => array('text_long'),
      'label' => t('Catalyst JS'),
    ),
    'catalyst_css_formatter' => array(
      'field types' => array('text_long'),
      'label' => t('Catalyst CSS'),
    ),
  );
}

/**
 * Implements hook_field_formatter_view().
 */
function catalyst_core_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display) {
  switch ($display['type']) {
    case 'catalyst_php_include':
      catalyst_include('entity');
      $item = array_shift($items);
      catalyst_entity_preprocess_php($entity_type, $entity, $item['value']);
      return array();
    case 'catalyst_php_preprocess':
      catalyst_include('entity');
      $item = array_shift($items);
      catalyst_entity_preprocess_php($entity_type, $entity, $item['value']);
      return array();
    case 'catalyst_twig_formatter':
    case 'catalyst_twig_wrapper':
      $item = array_shift($items);
      return array(array(
        '#post_render' => array(sprintf('%s_post_render', $display['type'])),
        '#entity_type' => $entity_type,
        '#entity' => $entity,
        '#value' => $item['value'],
      ));
    case 'catalyst_js_formatter':
      catalyst_include('entity');
      $fn = $field['field_name'];
      $scope = str_replace(array('field__js','__'), '', $fn);
      $fname = empty($scope) ? 'custom' : $scope;
      $filepath = catalyst_entity_get_public_filepath('catalyst', $entity, $fname.'.js');
      if (empty($scope)) {
        $group = CATALYST_JS_OTHER;
      }
      elseif ($scope == 'layout') {
        $group = CATALYST_JS_LAYOUT;
      }
      elseif ($scope == 'page') {
        $group = CATALYST_JS_PAGE;
      }
      drupal_add_js($filepath, array(
        'group' => $group,
      ));
      break;
    case 'catalyst_css_formatter':
      catalyst_include('entity');
      $fn = $field['field_name'];
      $scope = str_replace(array('field__css','__'), '', $fn);
      $fname = empty($scope) ? 'custom' : $scope;
      $filepath = catalyst_entity_get_public_filepath('catalyst', $entity, $fname.'.css');
      if (empty($scope)) {
        $group = CATALYST_CSS_OTHER;
      }
      elseif ($scope == 'layout') {
        $group = CATALYST_CSS_LAYOUT;
      }
      elseif ($scope == 'page') {
        $group = CATALYST_CSS_PAGE;
      }
      drupal_add_css($filepath, array(
        'group' => $group,
      ));
      break;
  }
}

function catalyst_twig_formatter_post_render($content, $context) {
  $entity = &drupal_static('twig_render_entity', NULL);
  $entity = $context['#entity'];
  catalyst_include('entity');
  $template_filepath = catalyst_entity_twig_template_filepath($context['#entity_type'], $entity);
  catalyst_ensure_file_exists($template_filepath, $context['#value']);
  //$variables = array($entity->type => $entity->normalize()) + $entity->variables();
  $variables = $entity->variables();
  $result =  array('#markup' => catalyst_twig_render_template($template_filepath, $variables));
  $output = drupal_render($result);
  drupal_static_reset('twig_render_entity');
  return $output;
}

function catalyst_twig_wrapper_post_render($content, $context) {
  $context['#variables']['content'] = $content;
  return catalyst_twig_render_template($context['#template_filepath'], $context['#variables']);
}

/**
 * Workaround for this issue with entity_metadata_wrapper:
 * https://www.drupal.org/node/1596594
 *
 * @code
 * $entity = entity_load_single('user', 1);
 * $myfield_value = entity_valval($entity->wraper()->field_myfield);
 * @endcode
 *
 * @param $data
 *   An EntityStructureWrapper
 * @return
 *   The value of the $data's value object's value attribute.
 */
function entity_valval(EntityStructureWrapper $data) {
  if ($data->value()) {
    return $data->value->value();
  }
}

/**
 *
 * @param $code string
 *   A string of php code without opening and closing tags.
 *
 * @param $variables array
 *   An array of variables that the $code is able to modify. $variables are
 *   intended for a template.
 * @return NULL or boolean
 *   Evaluations with catalyst_eval() must return null or boolean. Code
 *   processed by catalyst_eval() should never return a string. An exception
 *   will be thrown anticipating a syntax error when a string is returned.
 * @param array $___exportvars
 *   Array of "non-$variables" variables that the code cannot modify. Export
 *   vars are accessible at the top-level of evaluations, but are not
 *   passed on to templates (but can be manually in preprocessing).
 *
 * @todo Improve exception error message/handling for better debugging.
 */
function catalyst_eval($code, &$variables, $___exportvars = array()) {
  extract($___exportvars);
  unset($___exportvars);
  ob_start();
  $result = eval($code);
  $output = ob_get_contents();
  ob_end_clean();
  if (!in_array($result, array(NULL, TRUE, FALSE, 0, 1))) {
    throw new Exception($output);
  }
  return $result;
}
