<?php
/**
 * @file
 * Code for the Catalyst Doctype feature.
 */

include_once 'catalyst_doctype.features.inc';

/**
 * Implements hook_entity_import_alter().
 */
function catalyst_doctype_entity_import_alter($values, $entity, $entity_type) {
  if ($entity_type == 'catalyst' && $entity->type == 'doctype') {
    if (!empty($values['charset'])) {
      $entity->wrapper()->field__doctype_charset->set($values['charset']);
    }
    if (!empty($values['content_type'])) {
      $entity->wrapper()->field__doctype_content_type->set($values['content_type']);
    }
  }
  elseif (!empty($values['doctype'])) {

  }
}


/**
 * Implements hook_entity_export_alter().
 */
function catalyst_doctype_entity_export_alter(&$vars, $entity, $entity_type) {
  if ($entity_type == 'catalyst' && $entity->type == 'doctype') {
    if (!empty($entity->field__doctype_charset)) {
      $vars['charset'] = $entity->wrapper()->field__doctype_charset->value();
    }
    if (!empty($entity->field__doctype_content_type)) {
      $vars['content_type'] = $entity->wrapper()->field__doctype_content_type->value();
    }
    unset($vars['field__doctype_charset'], $vars['field__doctype_content_type']);
  }
  else if (!empty($vars['field__doctype'])) {
    $vars['doctype'] = $entity->wrapper()->field__doctype->value()->normalize();
    unset($vars['field__doctype']);
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function catalyst_doctype_form_eck__entity__form_alter(&$form, &$form_state, $form_id) {
  // Set the default value for the doctype content
  if (isset($form['field__body']) && catalyst_entity_is_new($form['#entity'])
    && $form['#entity']->type == 'doctype') {
    $form['field__body'][LANGUAGE_NONE][0]['#after_build'][] = 'field__body_set_default_value';
  }
}

/**
 * After build callback for setting the doctype content default value.
 *
 * @see catalyst_doctype_form_alter().
 */
function field__body_set_default_value($element) {
  if (empty($element['#value'])) {
    $element['#value'] = field__body_default_value();
  }
  return $element;
}

function field__body_default_value() {
  return implode("\n", array(
    '<html>',
    '  <head>',
    '    {{ head }}',
    '    <title>{{ head_title }}</title>',
    '    {{ styles }}',
    '    {{ scripts }}',
    '  </head>',
    '  <body>',
    '    {{ page_top }}',
    '    {{ page }}',
    '    {{ page_bottom }}',
    '  </body>',
    '</html>',
  ));
}
